import type { AnnouncementPriority } from '../enums/content';
import type { AnnouncementType } from '../enums/content';
import type { ContentOwnerType } from '../enums/content';
import type { NewsStatus } from '../enums/content';
import type { MediaAsset } from './common';
import type { ContentSection } from './common';
import type { ApprovalSummary } from './common';
import type { OfficerItem } from './common';
import type { AwardItem } from './common';
import type { AttachmentItem } from './common';

export type Announcement = {
  _id: string;
  title: string;
  content?: string;
  bodyHtml: string;
  priority: AnnouncementPriority;
  type: AnnouncementType;
  author: string | { firstName: string; lastName: string; email: string };
  ownerType: ContentOwnerType;
  organizationId?: string | null;
  isActive: boolean;
  targetAudience: string[];
  expiresAt?: string;
  coverImage?: MediaAsset;
  gallery: MediaAsset[];
  sections: ContentSection[];
  imageUrl?: string;
  status?: NewsStatus;
  publishedAt?: string;
  archivedAt?: string;
  approvalSummary?: ApprovalSummary;
  processInstanceId?: string | null;
  subtype?: string;
  effectiveDate?: string;
  termStart?: string;
  termEnd?: string;
  relatedOrganizationId?: string;
  relatedEventId?: string;
  approvalSource?: string;
  contactName?: string;
  contactEmail?: string;
  ctaLabel?: string;
  ctaUrl?: string;
  officerItems?: OfficerItem[];
  outgoingOfficerItems?: OfficerItem[];
  awardItems?: AwardItem[];
  attachmentItems?: AttachmentItem[];
  createdAt: string;
  updatedAt: string;
};
