import type { ContentOwnerType } from '../enums/content';
import type { EventStatus } from '../enums/content';
import type { MediaAsset } from './common';
import type { ContentSection } from './common';
import type { EventScheduleItem } from './common';
import type { ApprovalSummary } from './common';
import type { SpeakerItem } from './common';
import type { VenueDetails } from './common';
import type { AttachmentItem } from './common';

export type Event = {
  _id: string;
  title: string;
  description?: string;
  bodyHtml: string;
  excerpt: string;
  organizer: string | { firstName: string; lastName: string; email: string };
  ownerType: ContentOwnerType;
  organizationId?: string | null;
  startDate: string;
  endDate: string;
  location: string;
  status: EventStatus | string;
  publishedAt?: string;
  cancelledAt?: string;
  completedAt?: string;
  attendees: string[];
  maxAttendees?: number;
  coverImage?: MediaAsset;
  gallery: MediaAsset[];
  sections: ContentSection[];
  schedule: EventScheduleItem[];
  imageUrl?: string;
  tags?: string[];
  isRegistrationOpen: boolean;
  registeredCount?: number;
  checkedInCount?: number;
  registrationCloseAt?: string;
  allowWalkIns?: boolean;
  targetProgramIds?: string[];
  targetYearLevelIds?: string[];
  targetSectionIds?: string[];
  approvalSummary?: ApprovalSummary;
  processInstanceId?: string | null;
  registrationUrl?: string;
  registrationDeadline?: string;
  contactName?: string;
  contactEmail?: string;
  contactPhone?: string;
  hostOrganizationIds?: string[];
  coHostOrganizationIds?: string[];
  speakerItems?: SpeakerItem[];
  audience?: string;
  eligibility?: string;
  feeLabel?: string;
  certificateInfo?: string;
  venueDetails?: VenueDetails;
  mapUrl?: string;
  meetingUrl?: string;
  requirements?: string;
  attachmentItems?: AttachmentItem[];
  posterCaption?: string;
  createdAt: string;
  updatedAt: string;
};
