import type { ContentOwnerType } from '../enums/content';
import type { NewsStatus } from '../enums/content';
import type { MediaAsset } from './common';
import type { ContentSection } from './common';
import type { ApprovalSummary } from './common';
import type { ReferenceLink } from './common';
import type { AttachmentItem } from './common';

export type News = {
  _id: string;
  title: string;
  content?: string;
  bodyHtml: string;
  excerpt: string;
  author: string | { firstName: string; lastName: string; email: string };
  ownerType: ContentOwnerType;
  organizationId?: string | null;
  status: NewsStatus;
  publishedAt?: string;
  archivedAt?: string;
  approvalSummary?: ApprovalSummary;
  processInstanceId?: string | null;
  tags: string[];
  coverImage?: MediaAsset;
  gallery: MediaAsset[];
  sections: ContentSection[];
  imageUrl?: string;
  category?: string;
  featured?: boolean;
  pinned?: boolean;
  sourceUrl?: string;
  referenceLinks?: ReferenceLink[];
  attachmentItems?: AttachmentItem[];
  readingTime?: number;
  authorDisplayName?: string;
  authorRole?: string;
  associatedEventId?: string;
  associatedOrganizationId?: string;
  spotlightLabel?: string;
  seoDescription?: string;
  canonicalSlug?: string;
  relatedArticleIds?: string[];
  createdAt: string;
  updatedAt: string;
};
