export const queryKeys = {
  auth: ['auth'] as const,
  me: ['student', 'me'] as const,
  updates: ['updates'] as const,
  studentEvents: ['student', 'events'] as const,
  publicEvent: (eventId: string) => ['public', 'event', eventId] as const,
  registration: (eventId: string) => ['student', 'registration', eventId] as const,
  registrations: ['student', 'registrations'] as const,
  attendance: ['student', 'attendance'] as const,
  news: ['news'] as const,
  newsDetail: (id: string) => ['news', id] as const,
  announcements: ['announcements'] as const,
  announcementDetail: (id: string) => ['announcements', id] as const,
  memberships: ['student', 'memberships'] as const,
  membershipStatus: (orgId: string) => ['student', 'membership-status', orgId] as const,
  organizations: ['organizations'] as const,
  organizationDetail: (id: string) => ['organizations', id] as const,
  orgVotes: (orgId: string) => ['student', 'org-votes', orgId] as const,
  orgVote: (orgId: string, voteId: string) => ['student', 'org-votes', orgId, voteId] as const,
  orgVoteResults: (orgId: string, voteId: string) =>
    ['student', 'org-votes', orgId, voteId, 'results'] as const,
};
