import mongoose from 'mongoose';
import '../config/loadEnv';
import User from '../models/User';
import Role from '../models/Role';
import News from '../models/News';
import Announcement from '../models/Announcement';
import Event from '../models/Event';
import Organization from '../models/Organization';
import { UserRole, Permission, NewsStatus, AnnouncementPriority, AnnouncementType, EventStatus, ContentOwnerType } from '../types';
import logger from '../utils/logger';
import { validateEnv } from '../config/validateEnv';

const seedDatabase = async () => {
  try {
    validateEnv();

    // Connect to MongoDB
    const mongoURI = process.env.MONGODB_URI;
    if (!mongoURI) {
      throw new Error('MONGODB_URI is required');
    }
    await mongoose.connect(mongoURI);
    logger.info('Connected to MongoDB');

    // Clear existing data
    await User.deleteMany({});
    await Role.deleteMany({});
    await News.deleteMany({});
    await Announcement.deleteMany({});
    await Event.deleteMany({});
    await Organization.deleteMany({});
    logger.info('Cleared existing data');

    // Create default admin user
    const adminEmail = 'admin@cict.edu';
    const existingAdmin = await User.findOne({ email: adminEmail });

    if (!existingAdmin) {
      const admin = await User.create({
        email: adminEmail,
        password: 'Admin@123456', // Change this in production!
        firstName: 'System',
        lastName: 'Administrator',
        role: UserRole.FULL_ADMIN,
        isActive: true,
      });
      logger.info(`✅ Default admin created: ${admin.email}`);
      logger.info(`   Password: Admin@123456 (CHANGE THIS!)`);
    } else {
      logger.info('Admin user already exists');
    }

    // Create system roles with default permissions
    const systemRoles = [
      {
        name: 'Content Manager',
        description: 'Can manage news and announcements',
        permissions: [
          Permission.CREATE_NEWS,
          Permission.EDIT_NEWS,
          Permission.DELETE_NEWS,
          Permission.PUBLISH_NEWS,
          Permission.ARCHIVE_NEWS,
          Permission.VIEW_NEWS,
          Permission.CREATE_ANNOUNCEMENT,
          Permission.EDIT_ANNOUNCEMENT,
          Permission.DELETE_ANNOUNCEMENT,
          Permission.PUBLISH_ANNOUNCEMENT,
          Permission.ARCHIVE_ANNOUNCEMENT,
          Permission.VIEW_ANNOUNCEMENT,
          Permission.VIEW_EVENT,
          Permission.CREATE_EVENT,
          Permission.EDIT_EVENT,
          Permission.PUBLISH_EVENT,
          Permission.CANCEL_EVENT,
          Permission.COMPLETE_EVENT,
          Permission.VIEW_ORGANIZATION,
          Permission.CREATE_ORGANIZATION,
          Permission.EDIT_ORGANIZATION,
          Permission.VIEW_ROLE,
        ],
        isSystemRole: true,
      },
      {
        name: 'Member Manager',
        description: 'Can manage members and view content',
        permissions: [
          Permission.CREATE_MEMBER,
          Permission.EDIT_MEMBER,
          Permission.DELETE_MEMBER,
          Permission.VIEW_MEMBER,
          Permission.VIEW_NEWS,
          Permission.VIEW_ANNOUNCEMENT,
          Permission.VIEW_EVENT,
          Permission.VIEW_ORGANIZATION,
        ],
        isSystemRole: true,
      },
      {
        name: 'Viewer',
        description: 'Can only view content',
        permissions: [
          Permission.VIEW_NEWS,
          Permission.VIEW_ANNOUNCEMENT,
          Permission.VIEW_MEMBER,
          Permission.VIEW_EVENT,
          Permission.VIEW_ORGANIZATION,
        ],
        isSystemRole: true,
      },
    ];

    const admin = await User.findOne({ email: adminEmail });
    if (!admin) {
      logger.error('Admin user not found');
      process.exit(1);
    }

    for (const roleData of systemRoles) {
      const existingRole = await Role.findOne({ name: roleData.name });
      if (!existingRole) {
        const role = await Role.create({
          ...roleData,
          createdBy: admin._id.toString(),
        });
        logger.info(`✅ System role created: ${role.name}`);
      } else {
        logger.info(`System role already exists: ${roleData.name}`);
      }
    }

    // Create News and Announcements
    const newsData = [
        {
          title: 'CICT Hosts Annual Hackathon 2024: Code for Change',
          excerpt: 'Over 200 students participated in a 48-hour coding marathon, building innovative solutions for real-world community problems.',
          content: 'The College of Information and Communication Technology successfully hosted its Annual Hackathon 2024, bringing together over 200 student developers for an intense 48-hour coding competition. Teams built innovative solutions addressing community challenges in healthcare, education, and sustainability.',
          bodyHtml: '<p>The College of Information and Communication Technology successfully hosted its Annual Hackathon 2024, bringing together over 200 student developers for an intense 48-hour coding competition. Teams built innovative solutions addressing community challenges in healthcare, education, and sustainability.</p><p>The winning team developed an AI-powered waste management system, while runners-up created a mobile health monitoring app for senior citizens.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660324/ict4_qnkh2y.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660324/ict4_qnkh2y.jpg',
            alt: 'CICT Hackathon 2024',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Hackathon', 'Innovation', 'Competition'],
          publishedAt: new Date('2024-03-15'),
        },
        {
          title: 'ICT-SF Hosts Annual Student Leadership Summit',
          excerpt: 'Student leaders from all five CICT organizations gathered for a day of leadership training, team building, and strategic planning.',
          content: 'The ICT Student Forum organized the Annual Student Leadership Summit, bringing together officers and committee heads from all five CICT organizations. The summit featured workshops on effective communication, project management, and conflict resolution led by industry professionals.',
          bodyHtml: '<p>The ICT Student Forum organized the Annual Student Leadership Summit, bringing together officers and committee heads from all five CICT organizations.</p><p>The summit featured workshops on effective communication, project management, and conflict resolution led by industry professionals. Participants also engaged in strategic planning sessions to align organizational goals for the upcoming academic year.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335708/photo_2024-09-22_21-31-55_2_y2irl5.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335708/photo_2024-09-22_21-31-55_2_y2irl5.jpg',
            alt: 'Student Leadership Summit',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'ict-sf',
          tags: ['Leadership', 'Organizations', 'Community'],
          publishedAt: new Date('2024-02-20'),
        },
        {
          title: 'CICT Partners with Top Tech Companies for Internship Program',
          excerpt: 'A new partnership program connects CICT students with internship opportunities at leading technology companies across Metro Manila.',
          content: 'The College of Information and Communication Technology has signed partnership agreements with five leading technology companies to provide internship opportunities for BS Computer Science and BS Information Systems students. The program offers hands-on experience in software development, data analytics, and IT consulting.',
          bodyHtml: '<p>The College of Information and Communication Technology has signed partnership agreements with five leading technology companies to provide internship opportunities for BS Computer Science and BS Information Systems students.</p><p>The program offers hands-on experience in software development, data analytics, and IT consulting, with participating companies committed to hiring top-performing interns for full-time positions upon graduation.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
            alt: 'Industry Partnership',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Partnership', 'Career', 'Industry'],
          publishedAt: new Date('2024-01-25'),
        },
        {
          title: 'ROBOTCU Wins National Robotics Innovation Challenge',
          excerpt: 'The Robotics Club University team took home first place at the National Robotics Innovation Challenge with their autonomous delivery robot.',
          content: 'ROBOTCU brought pride to CICT by winning the National Robotics Innovation Challenge. The team designed and built an autonomous delivery robot capable of navigating complex indoor environments using AI-powered computer vision and sensor fusion technology.',
          bodyHtml: '<p>ROBOTCU brought pride to CICT by winning the National Robotics Innovation Challenge. The team designed and built an autonomous delivery robot capable of navigating complex indoor environments.</p><p>The robot uses AI-powered computer vision and sensor fusion technology to detect obstacles, plan optimal routes, and deliver packages safely to designated locations. The team received a trophy and grant funding for future research.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939316/500122427_681028194557259_7080048757823211543_n_yeecku.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939316/500122427_681028194557259_7080048757823211543_n_yeecku.jpg',
            alt: 'ROBOTCU National Champions',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'robotcu',
          tags: ['Robotics', 'Competition', 'Innovation', 'Award'],
          publishedAt: new Date('2024-04-10'),
        },
        {
          title: 'CSS Organizes First-Ever AI Ethics Symposium',
          excerpt: 'Computer Science Society brings together students, faculty, and industry experts to discuss the ethical implications of artificial intelligence.',
          content: 'The Computer Science Society hosted the inaugural AI Ethics Symposium, featuring keynote speakers from academia and industry who explored topics including algorithmic bias, data privacy, and responsible AI development. Over 300 students attended the day-long event.',
          bodyHtml: '<p>The Computer Science Society hosted the inaugural AI Ethics Symposium, featuring keynote speakers from academia and industry who explored topics including algorithmic bias, data privacy, and responsible AI development.</p><p>Over 300 students attended the day-long event, participating in panel discussions and interactive workshops that challenged them to think critically about the societal impact of the technologies they will build.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Academics_nb0eat.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Academics_nb0eat.jpg',
            alt: 'AI Ethics Symposium',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'css',
          tags: ['AI', 'Ethics', 'Symposium', 'Research'],
          publishedAt: new Date('2024-03-28'),
        },
        {
          title: 'CICT Campus Life Festival Draws Record Attendance',
          excerpt: 'The annual Campus Life Festival brought together over 5,000 students for a week of sports, cultural performances, and community activities.',
          content: 'The CICT Campus Life Festival was a resounding success, attracting a record 5,000+ attendees across a week-long celebration. Activities included intramural sports tournaments, a cultural night showcasing student talents, an org fair, and a community service day.',
          bodyHtml: '<p>The CICT Campus Life Festival was a resounding success, attracting a record 5,000+ attendees across a week-long celebration.</p><p>Activities included intramural sports tournaments, a cultural night showcasing student talents, an org fair where all five student organizations recruited new members, and a community service day where students volunteered at local schools and barangay centers.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
            alt: 'Campus Life Festival',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Campus Life', 'Festival', 'Community', 'Sports'],
          publishedAt: new Date('2024-02-14'),
        },
        {
          title: 'ISS Launches Business Analytics Laboratory',
          excerpt: 'The Information Systems Society opens a state-of-the-art business analytics lab equipped with industry-standard tools and software.',
          content: 'The Information Systems Society inaugurated the new Business Analytics Laboratory, a dedicated workspace equipped with Tableau, Power BI, SQL servers, and ERP simulation software. The lab will support IS students in coursework, research projects, and consulting engagements with local businesses.',
          bodyHtml: '<p>The Information Systems Society inaugurated the new Business Analytics Laboratory, a dedicated workspace equipped with Tableau, Power BI, SQL servers, and ERP simulation software.</p><p>The lab will support IS students in coursework, research projects, and consulting engagements with local businesses. ISS President Gabriel Villanueva described the lab as a significant step toward bridging classroom learning with real-world business technology practice.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
            alt: 'Business Analytics Lab',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'iss',
          tags: ['Information Systems', 'Analytics', 'Technology', 'Academics'],
          publishedAt: new Date('2024-03-05'),
        },
        {
          title: 'BEST Exchange Program Welcomes International Students',
          excerpt: 'The Board of European Students of Technology welcomes exchange students from partner universities across Europe for a semester of cultural and academic exchange.',
          content: 'BEST CICT chapter launched its international exchange program, welcoming 15 students from partner universities in Germany, Poland, Spain, and Italy. The exchange students will take CICT courses while participating in cultural immersion activities, language exchanges, and collaborative tech projects.',
          bodyHtml: '<p>BEST CICT chapter launched its international exchange program, welcoming 15 students from partner universities in Germany, Poland, Spain, and Italy.</p><p>The exchange students will take CICT courses while participating in cultural immersion activities, language exchanges, and collaborative tech projects with local CICT students. The program aims to foster global perspectives and cross-cultural collaboration in technology education.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
            alt: 'BEST Exchange Program',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'best',
          tags: ['International', 'Exchange', 'Cultural', 'Collaboration'],
          publishedAt: new Date('2024-01-10'),
        },
        {
          title: 'CICT Student Clinches Gold at International Programming Olympiad',
          excerpt: 'A CICT Computer Science student brought home the gold medal from the prestigious International Collegiate Programming Olympiad held in Singapore.',
          content: 'Fourth-year BS Computer Science student Paolo Miguel Santos represented the Philippines at the International Collegiate Programming Olympiad in Singapore, securing the gold medal in the Algorithmic Problem Solving category. Competing against 300+ participants from 50 countries, Santos solved six complex algorithmic problems in under four hours.',
          bodyHtml: '<p>Fourth-year BS Computer Science student Paolo Miguel Santos represented the Philippines at the International Collegiate Programming Olympiad in Singapore, securing the gold medal in the Algorithmic Problem Solving category.</p><p>Competing against 300+ participants from 50 countries, Santos solved six complex algorithmic problems in under four hours. His achievement marks the first gold medal for CICT in this international competition.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Academics_nb0eat.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Academics_nb0eat.jpg',
            alt: 'Programming Olympiad Gold Medalist',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Achievement', 'Programming', 'International', 'Competition'],
          publishedAt: new Date('2024-04-25'),
        },
        {
          title: 'CICT Faculty Published in Top-Tier Artificial Intelligence Journal',
          excerpt: 'Three CICT professors co-authored a groundbreaking research paper on explainable AI published in the Journal of Artificial Intelligence Research.',
          content: 'A research team led by Dr. Maria Elena Reyes, along with Prof. Juan Carlos Torres and Prof. Patricia Ann Lim, published their paper "Explainable Deep Learning for Medical Diagnosis" in the prestigious Journal of Artificial Intelligence Research. The paper presents a novel framework for making AI diagnostic models transparent and interpretable to medical professionals.',
          bodyHtml: '<p>A research team led by Dr. Maria Elena Reyes, along with Prof. Juan Carlos Torres and Prof. Patricia Ann Lim, published their paper "Explainable Deep Learning for Medical Diagnosis" in the prestigious Journal of Artificial Intelligence Research.</p><p>The paper presents a novel framework for making AI diagnostic models transparent and interpretable to medical professionals. This publication puts CICT on the map for cutting-edge AI research in Southeast Asia.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660324/ict4_qnkh2y.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660324/ict4_qnkh2y.jpg',
            alt: 'CICT Faculty Research Publication',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Research', 'AI', 'Faculty', 'Publication'],
          publishedAt: new Date('2024-05-10'),
        },
        {
          title: 'CICT Launches BS Data Science Program Starting AY 2025-2026',
          excerpt: 'The Commission on Higher Education has approved CICT\'s new Bachelor of Science in Data Science program, set to welcome its first cohort next academic year.',
          content: 'CICT is proud to announce the approval of its newest degree program — Bachelor of Science in Data Science. The four-year program will cover data engineering, machine learning, statistical modeling, big data analytics, and data ethics. The curriculum was designed in consultation with industry partners including data science teams from leading tech companies.',
          bodyHtml: '<p>CICT is proud to announce the approval of its newest degree program — Bachelor of Science in Data Science. The four-year program will cover data engineering, machine learning, statistical modeling, big data analytics, and data ethics.</p><p>The curriculum was designed in consultation with industry partners including data science teams from leading tech companies. Applications for the first cohort will open in November 2024.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
            alt: 'BS Data Science Program Launch',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Academics', 'Data Science', 'New Program', 'Curriculum'],
          publishedAt: new Date('2024-06-01'),
        },
        {
          title: 'ICT-SF Community Outreach: Tech Literacy Program for Senior Citizens',
          excerpt: 'ICT-SF volunteers launched a free tech literacy program teaching senior citizens basic computer skills, internet safety, and mobile app usage.',
          content: 'In partnership with the local barangay, ICT-SF launched "Tech Lola, Tech Lolo" — a community outreach program providing free technology literacy training to senior citizens. Over 50 volunteers from all five CICT organizations taught basic computer navigation, video calling with family, online safety, and essential mobile apps.',
          bodyHtml: '<p>In partnership with the local barangay, ICT-SF launched "Tech Lola, Tech Lolo" — a community outreach program providing free technology literacy training to senior citizens.</p><p>Over 50 volunteers from all five CICT organizations taught basic computer navigation, video calling with family, online safety, and essential mobile apps. The program runs every Saturday and has already served 150+ senior citizens in the community.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335708/photo_2024-09-22_21-31-55_2_y2irl5.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335708/photo_2024-09-22_21-31-55_2_y2irl5.jpg',
            alt: 'Tech Literacy for Seniors',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'ict-sf',
          tags: ['Community', 'Outreach', 'Tech Literacy', 'Service'],
          publishedAt: new Date('2024-06-15'),
        },
        {
          title: 'CICT Esports Tournament: Valorant Championship Draws 500+ Viewers',
          excerpt: 'The CICT Esports Committee hosted the semester\'s biggest gaming event with a Valorant tournament featuring 32 teams and over 500 live viewers.',
          content: 'The CICT Esports Committee organized the Valorant Inter-Organization Championship, bringing together 32 teams from all five CICT organizations for a weekend of competitive gaming. The grand finals were streamed live on Twitch, drawing over 500 concurrent viewers. Team CSS took home the championship trophy after an intense best-of-five series.',
          bodyHtml: '<p>The CICT Esports Committee organized the Valorant Inter-Organization Championship, bringing together 32 teams from all five CICT organizations for a weekend of competitive gaming.</p><p>The grand finals were streamed live on Twitch, drawing over 500 concurrent viewers. Team CSS took home the championship trophy after an intense best-of-five series against Team ISS in the grand finals.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939316/500122427_681028194557259_7080048757823211543_n_yeecku.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939316/500122427_681028194557259_7080048757823211543_n_yeecku.jpg',
            alt: 'CICT Esports Tournament',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Esports', 'Gaming', 'Tournament', 'Community'],
          publishedAt: new Date('2024-07-05'),
        },
        {
          title: 'CICT Research Team Secures PHP 5M DOST Grant for Smart Agriculture Project',
          excerpt: 'A multidisciplinary CICT research team has been awarded a PHP 5 million grant from DOST for developing IoT-based smart agriculture solutions for local farmers.',
          content: 'The Department of Science and Technology has awarded a PHP 5 million research grant to a CICT team led by Dr. Antonio Villar for their project "AgriSense: IoT-Driven Precision Agriculture for Smallholder Farmers." The project will deploy sensor networks and machine learning models to help local farmers optimize irrigation, pest control, and crop yield prediction.',
          bodyHtml: '<p>The Department of Science and Technology has awarded a PHP 5 million research grant to a CICT team led by Dr. Antonio Villar for their project "AgriSense: IoT-Driven Precision Agriculture for Smallholder Farmers."</p><p>The project will deploy sensor networks and machine learning models to help local farmers optimize irrigation, pest control, and crop yield prediction. Field trials will begin in three pilot municipalities across the province.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
            alt: 'DOST Smart Agriculture Grant',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Research', 'Grant', 'IoT', 'Agriculture', 'DOST'],
          publishedAt: new Date('2024-07-20'),
        },
        {
          title: 'CSS Mentorship Program Connects 200+ Students with Industry Professionals',
          excerpt: 'The Computer Science Society launched a mentorship program pairing 200+ CS students with alumni working at top tech companies for career guidance.',
          content: 'CSS launched the "CS Connect" mentorship program, matching over 200 computer science students with CICT alumni currently working at companies like Google, Accenture, Globe Telecom, and various tech startups. Mentors provide one-on-one career guidance, resume reviews, mock interviews, and industry insights through monthly virtual sessions.',
          bodyHtml: '<p>CSS launched the "CS Connect" mentorship program, matching over 200 computer science students with CICT alumni currently working at companies like Google, Accenture, Globe Telecom, and various tech startups.</p><p>Mentors provide one-on-one career guidance, resume reviews, mock interviews, and industry insights through monthly virtual sessions. The program has already received overwhelming positive feedback from both mentors and mentees.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939958/Messenger_creation_1447755149890924_v5hgih.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939958/Messenger_creation_1447755149890924_v5hgih.jpg',
            alt: 'CSS Mentorship Program',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'css',
          tags: ['Mentorship', 'Career', 'Alumni', 'Industry'],
          publishedAt: new Date('2024-08-01'),
        },
        {
          title: 'BEST Organizes Regional Tech Conference for ASEAN Students',
          excerpt: 'BEST CICT chapter hosted the ASEAN Student Technology Conference, bringing together 500+ students from 8 Southeast Asian countries for a week of learning and collaboration.',
          content: 'BEST CICT successfully organized the ASEAN Student Technology Conference 2024, a week-long event featuring keynote speeches from tech leaders, hands-on workshops, hackathon challenges, and cultural exchange activities. Students from the Philippines, Indonesia, Malaysia, Thailand, Vietnam, Singapore, Cambodia, and Brunei participated.',
          bodyHtml: '<p>BEST CICT successfully organized the ASEAN Student Technology Conference 2024, a week-long event featuring keynote speeches from tech leaders, hands-on workshops, hackathon challenges, and cultural exchange activities.</p><p>Students from the Philippines, Indonesia, Malaysia, Thailand, Vietnam, Singapore, Cambodia, and Brunei participated. The conference strengthened regional collaboration and inspired cross-border student innovation projects.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
            alt: 'ASEAN Tech Conference',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'best',
          tags: ['International', 'Conference', 'ASEAN', 'Collaboration'],
          publishedAt: new Date('2024-08-20'),
        },
        {
          title: 'CICT Alumna Named Forbes 30 Under 30 in Technology',
          excerpt: 'CICT alumna and tech entrepreneur Jasmine Reyes was recognized in Forbes 30 Under 30 Asia for her AI-powered edtech startup that serves millions of students.',
          content: 'CICT is proud to celebrate Jasmine Reyes (BS Computer Science, Batch 2018), who was named to Forbes 30 Under 30 Asia in the Technology category. Her startup, EduAI, uses artificial intelligence to personalize learning experiences for K-12 students and has raised USD 3 million in Series A funding, serving over 2 million students across Southeast Asia.',
          bodyHtml: '<p>CICT is proud to celebrate Jasmine Reyes (BS Computer Science, Batch 2018), who was named to Forbes 30 Under 30 Asia in the Technology category.</p><p>Her startup, EduAI, uses artificial intelligence to personalize learning experiences for K-12 students and has raised USD 3 million in Series A funding, serving over 2 million students across Southeast Asia.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326586/IMG_9662_hxo97w.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326586/IMG_9662_hxo97w.jpg',
            alt: 'CICT Alumna Forbes 30 Under 30',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Alumni', 'Achievement', 'Startup', 'Forbes', 'AI'],
          publishedAt: new Date('2024-09-01'),
        },
        {
          title: 'ISS Business Analytics Consulting Program Yields 10 Industry Projects',
          excerpt: 'The Information Systems Society consulting program completed 10 real-world business analytics projects with partner companies, generating actionable insights and student experience.',
          content: 'The ISS Consulting Program wrapped up its most productive semester yet, completing 10 business analytics projects for partner companies in retail, logistics, healthcare, and finance. Student consultants applied skills in data visualization, predictive modeling, and business intelligence to deliver actionable recommendations. Several students received job offers directly from partner companies.',
          bodyHtml: '<p>The ISS Consulting Program wrapped up its most productive semester yet, completing 10 business analytics projects for partner companies in retail, logistics, healthcare, and finance.</p><p>Student consultants applied skills in data visualization, predictive modeling, and business intelligence to deliver actionable recommendations. Several students received job offers directly from partner companies impressed by their work.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
            alt: 'ISS Consulting Program',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'iss',
          tags: ['Business Analytics', 'Consulting', 'Industry', 'Career'],
          publishedAt: new Date('2024-09-10'),
        },
        {
          title: 'ROBOTCU Represents Philippines at RoboCup Asia-Pacific 2024',
          excerpt: 'ROBOTCU was selected as the sole Philippine representative at the RoboCup Asia-Pacific competition in Bangkok, competing in the Rescue Robot category.',
          content: 'ROBOTCU made CICT proud by representing the Philippines at the RoboCup Asia-Pacific 2024 in Bangkok, Thailand. The team competed in the Rescue Robot category with their autonomous search-and-rescue robot "Kalasag," which navigated simulated disaster environments to locate victims. The team placed 4th out of 25 teams from 12 countries.',
          bodyHtml: '<p>ROBOTCU made CICT proud by representing the Philippines at the RoboCup Asia-Pacific 2024 in Bangkok, Thailand. The team competed in the Rescue Robot category with their autonomous search-and-rescue robot "Kalasag."</p><p>The robot navigated simulated disaster environments to locate victims using thermal imaging and AI-powered pathfinding. The team placed 4th out of 25 teams from 12 countries — the highest Philippine finish in RoboCup history.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939342/500442052_681027907890621_3151875760700323871_n_mkssn9.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939342/500442052_681027907890621_3151875760700323871_n_mkssn9.jpg',
            alt: 'ROBOTCU at RoboCup Asia-Pacific',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'robotcu',
          tags: ['Robotics', 'International', 'Competition', 'RoboCup', 'Achievement'],
          publishedAt: new Date('2024-09-15'),
        },
        {
          title: 'CICT Students Win Best Paper Award at International Conference on Computing',
          excerpt: 'A team of CICT undergraduate researchers won the Best Student Paper Award at ICC 2024 for their work on federated learning for healthcare data privacy.',
          content: 'CICT undergraduate researchers Maria Santos, Juan dela Cruz, and Angelo Reyes won the Best Student Paper Award at the International Conference on Computing 2024 held in Kuala Lumpur. Their paper "Privacy-Preserving Federated Learning for Multi-Hospital Patient Data Analysis" was selected from over 200 student submissions.',
          bodyHtml: '<p>CICT undergraduate researchers Maria Santos, Juan dela Cruz, and Angelo Reyes won the Best Student Paper Award at the International Conference on Computing 2024 held in Kuala Lumpur.</p><p>Their paper "Privacy-Preserving Federated Learning for Multi-Hospital Patient Data Analysis" was selected from over 200 student submissions. The research addresses the critical challenge of training AI models on sensitive medical data without compromising patient privacy.</p>',
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Student_Life2_tnlblr.jpg',
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Student_Life2_tnlblr.jpg',
            alt: 'Best Paper Award at ICC 2024',
          },
          status: NewsStatus.PUBLISHED,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          tags: ['Research', 'Achievement', 'Conference', 'AI', 'Federated Learning'],
          publishedAt: new Date('2024-09-25'),
        },
      ];

    await News.insertMany(newsData);
    logger.info('✅ News articles seeded (20 articles)');

    const announcementData = [
        {
          title: 'Enrollment for Academic Year 2024-2025 Now Open',
          content: 'Online enrollment is now open for incoming freshmen and returning students. Visit the admissions portal to complete your registration. Early enrollment runs from June 1 to July 15, 2024.',
          bodyHtml: '<p>Online enrollment is now open for incoming freshmen and returning students. Visit the admissions portal to complete your registration. Early enrollment runs from June 1 to July 15, 2024.</p><p>Requirements: Form 138 (Report Card), Certificate of Good Moral Character, PSA Birth Certificate, and 2x2 ID photos.</p>',
          priority: AnnouncementPriority.HIGH,
          type: AnnouncementType.ACADEMIC,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students', 'Prospective Students'],
          publishedAt: new Date('2024-05-15'),
          expiresAt: new Date('2024-07-16'),
        },
        {
          title: 'TechSkolar Platform Update: New Features Released',
          content: 'We have released new features on the TechSkolar platform including improved event registration, organization dashboards, and mobile QR check-in. Update your app to access the latest features.',
          bodyHtml: '<p>We have released new features on the TechSkolar platform including improved event registration, organization dashboards, and mobile QR check-in. Update your app to access the latest features.</p><p>Key updates: Real-time attendance tracking, organization membership management, event calendar sync, and enhanced notification system.</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.GENERAL,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Users'],
          publishedAt: new Date('2024-04-20'),
          expiresAt: new Date('2024-05-20'),
        },
        {
          title: 'Foundation Week 2024: Schedule of Activities',
          content: 'CICT Foundation Week will be held from August 12-16, 2024. Activities include the opening parade, academic competitions, sports tournaments, cultural night, and the Mr. & Ms. CICT pageant.',
          bodyHtml: '<p>CICT Foundation Week will be held from August 12-16, 2024. Mark your calendars for a week of celebration!</p><p>Activities include: Opening Parade (Aug 12), Academic Quiz Bee and Programming Competition (Aug 13), Intramural Finals (Aug 14), Cultural Night and Talent Showcase (Aug 15), and the Mr. & Ms. CICT Coronation Night (Aug 16).</p>',
          priority: AnnouncementPriority.HIGH,
          type: AnnouncementType.EVENT,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students', 'Faculty'],
          publishedAt: new Date('2024-07-20'),
          expiresAt: new Date('2024-08-17'),
        },
        {
          title: 'Important: Midterm Examination Guidelines',
          content: 'Midterm examinations for the Second Semester AY 2023-2024 will be held from April 15-19, 2024. Students must present their validated ID and examination permit.',
          bodyHtml: '<p>Midterm examinations for the Second Semester AY 2023-2024 will be held from April 15-19, 2024.</p><p>Requirements: Validated school ID, examination permit, and clearance from the Accounting Office. No permit, no exam policy will be strictly enforced. Contact your department coordinator for permit processing.</p>',
          priority: AnnouncementPriority.HIGH,
          type: AnnouncementType.ACADEMIC,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          targetAudience: ['All Students', 'Faculty'],
          publishedAt: new Date('2024-04-01'),
          expiresAt: new Date('2024-04-20'),
        },
        {
          title: 'Student Organization Recruitment Week',
          content: 'Discover your community! All five CICT student organizations — ICT-SF, CSS, ISS, ROBOTCU, and BEST — will be holding recruitment booths at the CICT lobby from May 6-10.',
          bodyHtml: '<p>Discover your community! All five CICT student organizations — ICT-SF, CSS, ISS, ROBOTCU, and BEST — will be holding recruitment booths at the CICT lobby from May 6-10.</p><p>Learn about each organization mission, programs, benefits, and how you can get involved. New members receive a welcome kit and access to exclusive events. Dont miss this chance to find your org family!</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.EVENT,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students'],
          publishedAt: new Date('2024-04-28'),
          expiresAt: new Date('2024-05-11'),
        },
        {
          title: 'Summer Coding Bootcamp Registration Now Open',
          content: 'CICT is offering intensive summer coding bootcamps in Web Development, Mobile App Development, and Data Science. Limited slots available. Registration closes May 30, 2024.',
          bodyHtml: '<p>CICT is offering intensive summer coding bootcamps in Web Development, Mobile App Development, and Data Science. Limited slots available — only 40 students per track.</p><p>Bootcamps run from June 10 to July 19, 2024. Fee: PHP 500 for currently enrolled students, PHP 1,500 for external participants. Register at the CICT office or online through the student portal.</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.ACADEMIC,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students'],
          publishedAt: new Date('2024-05-01'),
          expiresAt: new Date('2024-05-31'),
        },
        {
          title: 'Scholarship Applications Now Open for Academic Year 2024-2025',
          content: 'CICT is accepting scholarship applications for the upcoming academic year. Scholarships include Academic Excellence, Financial Assistance, Student Leadership, and Sports Development grants. Application deadline: July 30, 2024.',
          bodyHtml: '<p>CICT is accepting scholarship applications for the upcoming academic year. Available scholarships include:</p><ul><li>Academic Excellence Scholarship (GWA 1.50 or higher)</li><li>Financial Assistance Grant</li><li>Student Leadership Scholarship</li><li>Sports Development Grant</li></ul><p>Submit your application online through the student portal by July 30, 2024. Required documents: Latest grade report, income tax return (for financial aid), and recommendation letter.</p>',
          priority: AnnouncementPriority.HIGH,
          type: AnnouncementType.ACADEMIC,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students'],
          publishedAt: new Date('2024-06-01'),
          expiresAt: new Date('2024-07-31'),
        },
        {
          title: 'CICT Mental Health Awareness Week: October 7-11, 2024',
          content: 'Join CICT for Mental Health Awareness Week featuring free counseling sessions, stress management workshops, mindfulness activities, and a mental health resource fair. Your well-being matters.',
          bodyHtml: '<p>Join CICT for Mental Health Awareness Week from October 7-11, 2024. This year theme is "Digital Wellness: Balancing Tech and Mental Health."</p><p>Activities include: Free one-on-one counseling sessions, Art therapy workshops, Mindfulness and meditation sessions, Mental health resource fair, Peer support group orientation, and Digital detox challenge. All activities are free and confidential.</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.GENERAL,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students', 'Faculty'],
          publishedAt: new Date('2024-09-20'),
          expiresAt: new Date('2024-10-12'),
        },
        {
          title: 'Extended Library Hours During Midterm and Finals Period',
          content: 'The CICT Library will extend operating hours to 10:00 PM on weekdays and will be open on Saturdays (9:00 AM - 5:00 PM) during midterm (Oct 14-18) and finals (Dec 9-13) periods.',
          bodyHtml: '<p>The CICT Library will extend operating hours during the examination periods to support student study needs:</p><p>Midterm Period (October 14-18): Monday-Friday 7:00 AM - 10:00 PM, Saturday 9:00 AM - 5:00 PM.</p><p>Finals Period (December 9-13): Monday-Friday 7:00 AM - 10:00 PM, Saturday 9:00 AM - 5:00 PM.</p><p>Study rooms can be reserved through the library portal. Free coffee and snacks will be available after 7:00 PM.</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.ACADEMIC,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students'],
          publishedAt: new Date('2024-09-25'),
          expiresAt: new Date('2024-12-14'),
        },
        {
          title: 'Student Assistant Positions Available at CICT Laboratories',
          content: 'CICT is hiring student assistants for the Computer Laboratories, Robotics Lab, and Business Analytics Lab. Positions are open to 2nd year and above students with minimum GWA of 2.0.',
          bodyHtml: '<p>CICT is hiring student assistants for the following laboratories:</p><ul><li>Computer Laboratories (5 positions)</li><li>Robotics Laboratory (3 positions)</li><li>Business Analytics Laboratory (2 positions)</li></ul><p>Requirements: 2nd year standing or above, minimum GWA of 2.0, and willingness to work 15-20 hours per week. Compensation: PHP 60/hour. Submit your application and resume to the CICT Dean Office by October 4, 2024.</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.GENERAL,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students'],
          publishedAt: new Date('2024-09-15'),
          expiresAt: new Date('2024-10-05'),
        },
        {
          title: 'Scheduled Network Maintenance: October 5, 2024 (8:00 PM - 11:59 PM)',
          content: 'CICT network services including WiFi, computer labs, and online portals will be temporarily unavailable due to scheduled infrastructure upgrade on October 5 from 8:00 PM to 11:59 PM.',
          bodyHtml: '<p>CICT IT Services will conduct scheduled network infrastructure maintenance on Saturday, October 5, 2024 from 8:00 PM to 11:59 PM.</p><p>Services affected: Campus WiFi, Computer laboratory workstations, Student portal and LMS, Online library resources. Please save your work and plan accordingly. We apologize for any inconvenience.</p>',
          priority: AnnouncementPriority.HIGH,
          type: AnnouncementType.GENERAL,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Users'],
          publishedAt: new Date('2024-09-28'),
          expiresAt: new Date('2024-10-06'),
        },
        {
          title: 'Call for Papers: CICT Research Journal Volume 5',
          content: 'The CICT Research Journal is accepting manuscript submissions for Volume 5. Undergraduate and graduate students, faculty, and researchers are invited to submit original research papers in computing and technology.',
          bodyHtml: '<p>The CICT Research Journal is accepting manuscript submissions for Volume 5 (Publication Date: December 2024).</p><p>Topics: Artificial Intelligence & Machine Learning, Software Engineering & Development, Data Science & Analytics, Information Systems & Business Technology, Cybersecurity & Networks, Human-Computer Interaction, Robotics & Automation.</p><p>Submission deadline: November 15, 2024. Submit manuscripts through the CICT Research Portal. Accepted papers receive PHP 5,000 publication grant.</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.ACADEMIC,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students', 'Faculty'],
          publishedAt: new Date('2024-09-10'),
          expiresAt: new Date('2024-11-16'),
        },
        {
          title: 'CICT Alumni Homecoming 2024: Save the Date!',
          content: 'Mark your calendars for the CICT Alumni Homecoming on December 7, 2024. All CICT graduates are invited for a night of reunion, networking, and celebration of achievements.',
          bodyHtml: '<p>Calling all CICT alumni! Join us for the Annual Alumni Homecoming on Saturday, December 7, 2024 from 4:00 PM to 10:00 PM at the CICT Auditorium.</p><p>Program highlights: Alumni achievement awards, Batch reunion corners, Alumni vs. Student friendly games, Networking dinner, and Live band performance.</p><p>Registration fee: PHP 500 (proceeds go to the CICT Scholarship Fund). Register at the CICT Alumni Office or online through the alumni portal.</p>',
          priority: AnnouncementPriority.MEDIUM,
          type: AnnouncementType.EVENT,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students', 'Faculty', 'All Users'],
          publishedAt: new Date('2024-10-01'),
          expiresAt: new Date('2024-12-08'),
        },
        {
          title: 'New Student Portal Features: Grade Tracking and Course Enrollment Preview',
          content: 'The CICT Student Portal has been updated with new features including real-time grade tracking, course enrollment preview for next semester, and automated curriculum audit.',
          bodyHtml: '<p>The CICT Student Portal has been updated with exciting new features to enhance your academic experience:</p><ul><li>Real-time Grade Tracking — See your grades as soon as they are posted</li><li>Course Enrollment Preview — Plan your next semester schedule in advance</li><li>Automated Curriculum Audit — Track your progress toward graduation requirements</li><li>Notification Center — Get alerts for enrollment deadlines, grade postings, and announcements</li></ul><p>Log in to the student portal to explore these features. Feedback and suggestions are welcome through the Help Center.</p>',
          priority: AnnouncementPriority.LOW,
          type: AnnouncementType.GENERAL,
          status: NewsStatus.PUBLISHED,
          isActive: true,
          author: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          targetAudience: ['All Students'],
          publishedAt: new Date('2024-10-10'),
          expiresAt: new Date('2024-12-31'),
        },
      ];

    await Announcement.insertMany(announcementData);
    logger.info('✅ Announcements seeded (14 announcements)');

    // Create Events
    const eventData = [
        {
          title: 'CICT Foundation Week 2024',
          description: 'A week-long celebration of CICT\'s founding anniversary featuring academic competitions, sports tournaments, cultural performances, and community activities.',
          bodyHtml: '<p>A week-long celebration of CICT\'s founding anniversary featuring academic competitions, sports tournaments, cultural performances, and community activities. Join us as we celebrate another year of excellence in technology education!</p>',
          excerpt: 'Join the CICT community in celebrating another year of excellence in technology education with a week of exciting activities and events.',
          organizer: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          startDate: new Date('2024-08-12T08:00:00'),
          endDate: new Date('2024-08-16T22:00:00'),
          location: 'CICT Campus Grounds',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-07-20'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
            alt: 'CICT Foundation Week 2024',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
          tags: ['Foundation Week', 'Celebration', 'Community', 'Campus Life'],
          isRegistrationOpen: true,
          maxAttendees: 0,
          schedule: [
            { label: 'Day 1', title: 'Opening Parade & Program', description: 'Grand opening ceremony and parade around the campus.' },
            { label: 'Day 2', title: 'Academic Competitions', description: 'Quiz Bee, Programming Contest, and Research Poster Exhibit.' },
            { label: 'Day 3', title: 'Sports Finals', description: 'Intramural championship games for basketball, volleyball, and esports.' },
            { label: 'Day 4', title: 'Cultural Night', description: 'Talent showcase, dance competitions, and live band performances.' },
            { label: 'Day 5', title: 'Awards & Closing Ceremony', description: 'Mr. & Ms. CICT coronation and recognition of outstanding students.' },
          ],
        },
        {
          title: 'Annual Hackathon: Code for Change',
          description: 'A 48-hour coding competition where student teams build innovative solutions addressing real-world community challenges.',
          bodyHtml: '<p>A 48-hour coding competition where student teams build innovative solutions addressing real-world community challenges. Open to all CICT students regardless of year level or programming experience.</p><p>Prizes: PHP 10,000 for 1st place, PHP 5,000 for 2nd place, and PHP 3,000 for 3rd place. All participants receive certificates and swag kits.</p>',
          excerpt: 'Build innovative tech solutions for real community problems in this 48-hour hackathon. PHP 10,000 grand prize!',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'css',
          startDate: new Date('2024-09-20T08:00:00'),
          endDate: new Date('2024-09-22T18:00:00'),
          location: 'CICT Computer Laboratories',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-08-15'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660324/ict4_qnkh2y.jpg',
            alt: 'Code for Change Hackathon',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660324/ict4_qnkh2y.jpg',
          tags: ['Hackathon', 'Coding', 'Competition', 'Innovation'],
          isRegistrationOpen: true,
          maxAttendees: 200,
          registrationCloseAt: new Date('2024-09-18T23:59:59'),
        },
        {
          title: 'Tech Career Fair 2024',
          description: 'Connect with leading tech companies for internship and job opportunities. Bring your resume and portfolio.',
          bodyHtml: '<p>Connect with leading tech companies for internship and job opportunities. Participating companies include top software firms, IT consultancies, and startup incubators from Metro Manila.</p><p>Activities include: Company booths, on-the-spot interviews, resume review station, career talks, and portfolio showcase. Bring multiple copies of your resume!</p>',
          excerpt: 'Meet recruiters from top tech companies. On-the-spot interviews and internship opportunities available.',
          organizer: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          startDate: new Date('2024-10-05T09:00:00'),
          endDate: new Date('2024-10-05T17:00:00'),
          location: 'CICT Auditorium',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-09-01'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
            alt: 'Tech Career Fair 2024',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
          tags: ['Career Fair', 'Internship', 'Jobs', 'Industry'],
          isRegistrationOpen: true,
          maxAttendees: 500,
          registrationCloseAt: new Date('2024-10-04T23:59:59'),
        },
        {
          title: 'ROBOTCU Workshop Series: Introduction to Robotics',
          description: 'Hands-on workshop series covering robot design, electronics, programming, and autonomous control. No prior experience needed.',
          bodyHtml: '<p>Hands-on workshop series covering robot design, electronics, programming, and autonomous control. Open to all CICT students regardless of program.</p><p>Series includes four sessions: Robot Design Basics, Electronics & Sensors, Programming with Arduino, and Autonomous Navigation. Participants who complete all four sessions receive a certificate from ROBOTCU.</p>',
          excerpt: 'Learn robotics from scratch! Four-session workshop covering design, electronics, and programming.',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'robotcu',
          startDate: new Date('2024-09-07T13:00:00'),
          endDate: new Date('2024-09-28T17:00:00'),
          location: 'CICT Robotics Laboratory',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-08-20'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939342/500442052_681027907890621_3151875760700323871_n_mkssn9.jpg',
            alt: 'ROBOTCU Workshop Series',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939342/500442052_681027907890621_3151875760700323871_n_mkssn9.jpg',
          tags: ['Robotics', 'Workshop', 'Hands-on', 'Engineering'],
          isRegistrationOpen: true,
          maxAttendees: 30,
          schedule: [
            { label: 'Week 1', title: 'Robot Design Basics', description: 'Principles of mechanical design and material selection.' },
            { label: 'Week 2', title: 'Electronics & Sensors', description: 'Working with motors, sensors, and microcontrollers.' },
            { label: 'Week 3', title: 'Programming with Arduino', description: 'Writing code to control robot movement and sensor input.' },
            { label: 'Week 4', title: 'Autonomous Navigation', description: 'Implementing pathfinding and obstacle avoidance algorithms.' },
          ],
        },
        {
          title: 'Information Systems Case Competition',
          description: 'Teams analyze real business cases and propose technology-driven solutions. Present your recommendations to a panel of industry judges.',
          bodyHtml: '<p>Teams of 3-4 IS students analyze real business cases and propose technology-driven solutions. Present your recommendations to a panel of industry judges from top consulting and tech firms.</p><p>Winners receive internship priority at partner companies, certificates, and cash prizes. This is an excellent opportunity to apply classroom knowledge to real business scenarios.</p>',
          excerpt: 'Apply your IS knowledge to solve real business cases. Compete for internship priority and cash prizes!',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'iss',
          startDate: new Date('2024-11-15T09:00:00'),
          endDate: new Date('2024-11-16T18:00:00'),
          location: 'CICT Conference Hall',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-10-20'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
            alt: 'IS Case Competition',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
          tags: ['Case Competition', 'Business', 'IS', 'Competition'],
          isRegistrationOpen: true,
          maxAttendees: 100,
          registrationCloseAt: new Date('2024-11-10T23:59:59'),
        },
        {
          title: 'BEST Cultural Exchange Night',
          description: 'An evening of cultural performances, international cuisine, and networking with exchange students from partner universities across Europe.',
          bodyHtml: '<p>An evening of cultural performances, international cuisine, and networking with exchange students from partner universities across Europe. Experience diverse cultures without leaving campus!</p><p>Highlights include: traditional dance performances, food tasting stations featuring dishes from 10 countries, language exchange corner, and a photo exhibit of previous exchange programs.</p>',
          excerpt: 'Experience cultures from across Europe! Food, performances, and networking with international exchange students.',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'best',
          startDate: new Date('2024-10-25T18:00:00'),
          endDate: new Date('2024-10-25T22:00:00'),
          location: 'CICT Student Center',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-10-01'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
            alt: 'BEST Cultural Exchange Night',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
          tags: ['Cultural', 'International', 'Exchange', 'Networking'],
          isRegistrationOpen: true,
          maxAttendees: 150,
        },
        {
          title: 'Student Leadership Summit 2024',
          description: 'A day of leadership training, team building, and strategic planning for student organization officers and aspiring leaders.',
          bodyHtml: '<p>A day of leadership training, team building, and strategic planning for student organization officers and aspiring leaders. This event has been completed successfully with over 80 participants.</p><p>Workshop topics included: Effective Communication, Conflict Resolution, Event Planning & Budgeting, and Building Inclusive Organizations. Thank you to all who participated!</p>',
          excerpt: 'A day of leadership training and team building for student leaders. Over 80 participants from all five CICT organizations.',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'ict-sf',
          startDate: new Date('2024-02-15T08:00:00'),
          endDate: new Date('2024-02-15T17:00:00'),
          location: 'CICT Auditorium',
          status: EventStatus.COMPLETED,
          publishedAt: new Date('2024-02-01'),
          completedAt: new Date('2024-02-15T17:00:00'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335708/photo_2024-09-22_21-31-55_2_y2irl5.jpg',
            alt: 'Student Leadership Summit 2024',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335708/photo_2024-09-22_21-31-55_2_y2irl5.jpg',
          tags: ['Leadership', 'Training', 'Organizations', 'Community'],
          isRegistrationOpen: false,
          maxAttendees: 100,
        },
        {
          title: 'ICT-SF General Assembly & Welcome Back',
          description: 'Welcome back event for all ICT students. Meet your student government, learn about upcoming activities, and get involved.',
          bodyHtml: '<p>Welcome back event for all ICT students! Meet your ICT-SF officers, learn about upcoming activities for the semester, and discover how you can get involved in student government and college-wide initiatives.</p><p>Free snacks and refreshments will be served. New students are especially encouraged to attend!</p>',
          excerpt: 'Welcome back, ICT students! Meet your student government and learn about exciting opportunities this semester.',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'ict-sf',
          startDate: new Date('2024-08-19T13:00:00'),
          endDate: new Date('2024-08-19T16:00:00'),
          location: 'CICT Auditorium',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-08-10'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
            alt: 'ICT-SF General Assembly',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
          tags: ['General Assembly', 'Welcome', 'Community', 'Student Government'],
          isRegistrationOpen: true,
          maxAttendees: 0,
        },
        {
          title: 'CSS Tech Talk Series: The Future of Quantum Computing',
          description: 'A technical seminar exploring the principles of quantum computing, current state of the technology, and its potential impact on cryptography, drug discovery, and optimization problems.',
          bodyHtml: '<p>A technical seminar exploring the principles of quantum computing, current state of the technology, and its potential impact on cryptography, drug discovery, and optimization problems.</p><p>Featuring guest speaker Dr. Raymond Chua from the National Institute of Physics, this talk will demystify quantum computing concepts and discuss how students can prepare for the quantum computing era. Q&A session and networking reception to follow.</p>',
          excerpt: 'Explore the fascinating world of quantum computing with guest speaker Dr. Raymond Chua. Learn how quantum will change computing forever.',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'css',
          startDate: new Date('2024-10-10T14:00:00'),
          endDate: new Date('2024-10-10T17:00:00'),
          location: 'CICT Auditorium',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-09-25'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Academics_nb0eat.jpg',
            alt: 'Quantum Computing Tech Talk',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Academics_nb0eat.jpg',
          tags: ['Tech Talk', 'Quantum Computing', 'Seminar', 'CSS'],
          isRegistrationOpen: true,
          maxAttendees: 200,
          registrationCloseAt: new Date('2024-10-09T23:59:59'),
        },
        {
          title: 'ISS Business Analytics Workshop: Mastering Tableau and Power BI',
          description: 'A hands-on workshop teaching students how to use Tableau and Power BI for data visualization, dashboard creation, and business intelligence reporting.',
          bodyHtml: '<p>A hands-on workshop teaching students how to use Tableau and Power BI for data visualization, dashboard creation, and business intelligence reporting.</p><p>Participants will work with real-world datasets to create interactive dashboards, learn best practices in data storytelling, and earn a certificate of completion. Laptops with the software pre-installed will be provided.</p>',
          excerpt: 'Hands-on workshop on Tableau and Power BI. Learn data visualization and dashboard creation with real-world datasets.',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'iss',
          startDate: new Date('2024-11-08T09:00:00'),
          endDate: new Date('2024-11-08T16:00:00'),
          location: 'CICT Business Analytics Lab',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-10-25'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
            alt: 'Tableau and Power BI Workshop',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939519/IMG_20250517_203753_807_ljfmdc.jpg',
          tags: ['Workshop', 'Data Analytics', 'Tableau', 'Power BI', 'ISS'],
          isRegistrationOpen: true,
          maxAttendees: 40,
          registrationCloseAt: new Date('2024-11-07T23:59:59'),
        },
        {
          title: 'ROBOTCU BattleBots Competition: Inter-Org Robotics Showdown',
          description: 'Watch student-built combat robots battle it out in an arena! Teams from all five CICT organizations design and build 3kg combat robots for a tournament-style competition.',
          bodyHtml: '<p>Watch student-built combat robots battle it out in an arena! Teams from all five CICT organizations will design and build 3kg combat robots for a double-elimination tournament.</p><p>Spectators welcome! Come cheer for your organization team. Prizes: PHP 5,000 for champion, PHP 3,000 for runner-up, and PHP 1,000 for Best Design Award. Robot inspections begin at 8:00 AM, battles start at 10:00 AM.</p>',
          excerpt: 'Inter-org robot combat tournament! Watch student-built battle bots fight for supremacy. PHP 5,000 grand prize!',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'robotcu',
          startDate: new Date('2024-11-22T09:00:00'),
          endDate: new Date('2024-11-22T17:00:00'),
          location: 'CICT Covered Court',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-11-01'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939342/500442052_681027907890621_3151875760700323871_n_mkssn9.jpg',
            alt: 'BattleBots Competition',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939342/500442052_681027907890621_3151875760700323871_n_mkssn9.jpg',
          tags: ['Robotics', 'Competition', 'BattleBots', 'Engineering', 'Tournament'],
          isRegistrationOpen: true,
          maxAttendees: 300,
          registrationCloseAt: new Date('2024-11-21T23:59:59'),
        },
        {
          title: 'ICT-SF Acquaintance Party 2024: Neon Nights',
          description: 'The biggest social event of the semester! Join the ICT-SF Acquaintance Party with a neon theme featuring DJ performances, dance competitions, games, and food stalls.',
          bodyHtml: '<p>The biggest social event of the semester! Join the ICT-SF Acquaintance Party with this year theme: "Neon Nights."</p><p>What to expect: Live DJ performances, Inter-org dance competition, Neon face painting booth, Photobooth with props, Food stalls from local vendors, and Raffle prizes including gadgets and gift certificates.</p><p>Dress code: Wear something neon or white! Glow sticks and neon accessories will be provided at the entrance. Tickets: PHP 150 for org members, PHP 200 for non-members.</p>',
          excerpt: 'The biggest social event of the semester! Neon theme, DJ performances, dance comp, and amazing raffle prizes. Don\'t miss it!',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'ict-sf',
          startDate: new Date('2024-11-29T18:00:00'),
          endDate: new Date('2024-11-29T23:00:00'),
          location: 'CICT Student Center & Grounds',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-11-10'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
            alt: 'ICT-SF Acquaintance Party',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
          tags: ['Social', 'Party', 'Acquaintance', 'ICT-SF', 'Community'],
          isRegistrationOpen: true,
          maxAttendees: 500,
          registrationCloseAt: new Date('2024-11-28T23:59:59'),
        },
        {
          title: 'CICT Career Development Seminar: Resume Building and Interview Mastery',
          description: 'A career development seminar featuring HR professionals from top companies who will share tips on crafting standout resumes, acing technical interviews, and building a professional online presence.',
          bodyHtml: '<p>A career development seminar featuring HR professionals from top tech companies who will share actionable tips on:</p><ul><li>Crafting standout resumes and cover letters that get noticed</li><li>Acing technical and behavioral interviews</li><li>Building a professional LinkedIn profile</li><li>Creating an impressive portfolio and GitHub presence</li><li>Navigating job offers and salary negotiations</li></ul><p>Bring your current resume for a free one-on-one review session with HR professionals after the seminar.</p>',
          excerpt: 'Get career-ready! HR pros share tips on resumes, interviews, LinkedIn, and portfolios. Free resume review included.',
          organizer: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          startDate: new Date('2024-10-18T13:00:00'),
          endDate: new Date('2024-10-18T17:00:00'),
          location: 'CICT Auditorium',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-10-01'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
            alt: 'Career Development Seminar',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335595/371046306_338487401938051_771479620405214262_n_rpkg1f.jpg',
          tags: ['Career', 'Resume', 'Interview', 'Professional Development'],
          isRegistrationOpen: true,
          maxAttendees: 250,
          registrationCloseAt: new Date('2024-10-17T23:59:59'),
        },
        {
          title: 'CICT Sports Fest 2024: Inter-Organization Tournament',
          description: 'A week-long sports tournament featuring basketball, volleyball, badminton, table tennis, and esports competitions between CICT organizations.',
          bodyHtml: '<p>A week-long sports tournament featuring competitions between CICT organizations:</p><ul><li>Basketball (5v5) — CICT Covered Court</li><li>Volleyball (6v6 mixed) — CICT Covered Court</li><li>Badminton (Singles & Doubles) — CICT Gym</li><li>Table Tennis — CICT Student Center</li><li>Esports: Mobile Legends & Valorant — Online + CICT Labs</li></ul><p>Registration is per organization. Each org can field one team per sport. Deadline for team lineups: November 25. Opening ceremony on December 2 at 8:00 AM.</p>',
          excerpt: 'Compete for your org! Basketball, volleyball, esports, and more. One week of sports and school spirit.',
          organizer: admin._id,
          ownerType: ContentOwnerType.SYSTEM,
          startDate: new Date('2024-12-02T08:00:00'),
          endDate: new Date('2024-12-06T18:00:00'),
          location: 'CICT Sports Facilities',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-11-15'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
            alt: 'CICT Sports Fest 2024',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335598/450328906_1014347616442600_380351381824664479_n_bfxjmp.jpg',
          tags: ['Sports', 'Tournament', 'Inter-Org', 'Competition', 'Esports'],
          isRegistrationOpen: true,
          maxAttendees: 0,
          schedule: [
            { label: 'Day 1', title: 'Opening Ceremony & Basketball Prelims', description: 'Opening parade, torch lighting, and basketball preliminary games.' },
            { label: 'Day 2', title: 'Volleyball & Badminton', description: 'Volleyball preliminary rounds and badminton singles matches.' },
            { label: 'Day 3', title: 'Esports Day', description: 'Mobile Legends and Valorant tournament finals.' },
            { label: 'Day 4', title: 'Table Tennis & Semifinals', description: 'Table tennis tournament and basketball/volleyball semifinals.' },
            { label: 'Day 5', title: 'Championship Games & Closing', description: 'Basketball and volleyball finals, awarding ceremony, and closing program.' },
          ],
        },
        {
          title: 'BEST Sustainability Hackathon: Green Tech Solutions for Campus',
          description: 'A 24-hour hackathon focused on building tech solutions that promote sustainability and reduce the campus carbon footprint. Open to all CICT students.',
          bodyHtml: '<p>A 24-hour hackathon focused on building technology solutions that promote environmental sustainability on campus.</p><p>Challenge tracks: Waste Management & Recycling Tech, Energy Efficiency Monitoring, Sustainable Transportation, Water Conservation Systems, and Eco-Education Platforms.</p><p>Prizes: PHP 8,000 for 1st place, PHP 5,000 for 2nd place, PHP 3,000 for 3rd place. Winning solutions may be implemented on campus. Meals and snacks provided throughout the event.</p>',
          excerpt: 'Build tech for a greener campus! 24-hour sustainability hackathon with PHP 8,000 grand prize. All skill levels welcome.',
          organizer: admin._id,
          ownerType: ContentOwnerType.ORGANIZATION,
          organizationId: 'best',
          startDate: new Date('2024-12-14T09:00:00'),
          endDate: new Date('2024-12-15T12:00:00'),
          location: 'CICT Computer Laboratories & Innovation Hub',
          status: EventStatus.PUBLISHED,
          publishedAt: new Date('2024-11-20'),
          coverImage: {
            imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
            alt: 'BEST Sustainability Hackathon',
          },
          imageUrl: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766945618/photo_45_2025-12-29_02-02-12_utofwa.jpg',
          tags: ['Hackathon', 'Sustainability', 'Green Tech', 'Innovation', 'BEST'],
          isRegistrationOpen: true,
          maxAttendees: 120,
          registrationCloseAt: new Date('2024-12-12T23:59:59'),
        },
      ];

    await Event.insertMany(eventData);
    logger.info('✅ Events seeded (15 events)');

    // Create Organizations
    const orgData = [
        {
          id: 'ict-sf',
          name: 'ICT-SF',
          fullName: 'ICT Student Forum',
          description: 'The premier student organization for all ICT students.',
          longDescription: 'The ICT Student Forum serves as the umbrella organization for the College of ICT, representing the student body and organizing college-wide events.',
          logo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660320/cict4_qqksfh.jpg', // Placeholder
          banner: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
          established: '2018',
          mission: 'To empower ICT students through holistic development and representation.',
          vision: 'To be the leading student organization fostering innovation and leadership.',
          values: ['Leadership', 'Service', 'Excellence'],
          achievements: ['Best Student Council 2023'],
          members: [
            {
              id: 'ictsf-president',
              name: 'Maria Clara Santos',
              position: 'President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335623/462569135_2056490288117874_4448142511748007889_n_jdifnl.jpg',
              bio: 'A dedicated student leader committed to representing the ICT student body and driving meaningful change across the college.',
              joinedDate: '2022',
            },
            {
              id: 'ictsf-vp',
              name: 'Jose Rizal Cruz',
              position: 'Vice President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660318/DSC_0124_n8lgm1.jpg',
              bio: 'Passionate about student welfare and organizational development within the ICT community.',
              joinedDate: '2022',
            },
            {
              id: 'ictsf-secretary',
              name: 'Andrea Mae Dela Cruz',
              position: 'Secretary',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Student_Life2_tnlblr.jpg',
              bio: 'Organized and detail-oriented, ensuring smooth communication and documentation across all ICT-SF activities.',
              joinedDate: '2023',
            },
            {
              id: 'ictsf-treasurer',
              name: 'Miguel Araneta Reyes',
              position: 'Treasurer',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326595/c3f81b43-9dd5-4cd0-87ef-89f2626c7e1a_amustm.jpg',
              bio: 'Managing the organizations finances with transparency and integrity to support student initiatives.',
              joinedDate: '2023',
            },
          ],
          color: {
            primary: '#6e29f6',
            secondary: '#f629a8',
            accent: '#29f6d2',
          },
        },
        {
          id: 'css',
          name: 'CSS',
          fullName: 'Computer Science Society',
          description: 'The academic organization for Computer Science students.',
          longDescription: 'CSS promotes academic excellence and technological advancement in the field of Computer Science.',
          logo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660320/cict4_qqksfh.jpg',
          banner: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
          established: '2019',
          mission: 'To advance computer science education and practice.',
          vision: 'A community of world-class computer scientists.',
          values: ['Innovation', 'Logic', 'Creativity'],
          achievements: ['National Coding Champions 2024'],
          members: [
            {
              id: 'css-president',
              name: 'Angelo Bautista Tan',
              position: 'President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939958/Messenger_creation_1447755149890924_v5hgih.jpg',
              bio: 'Advancing computer science excellence through research, competitions, and community-driven tech initiatives.',
              joinedDate: '2021',
            },
            {
              id: 'css-vp',
              name: 'Sofia Isabelle Lim',
              position: 'Vice President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335631/462646799_491422266587695_2829599647701455693_n_ehk9wu.png',
              bio: 'Leading academic support programs and mentorship initiatives within the computer science community.',
              joinedDate: '2022',
            },
            {
              id: 'css-secretary',
              name: 'Rafael Consunji Ong',
              position: 'Secretary',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660333/IMG_4857_ew1wp8.jpg',
              bio: 'Coordinating symposium logistics and maintaining the society documentation and knowledge base.',
              joinedDate: '2022',
            },
          ],
          color: {
            primary: '#2563eb',
            secondary: '#60a5fa',
            accent: '#fbbf24',
          },
        },
        {
          id: 'iss',
          name: 'ISS',
          fullName: 'Information Systems Society',
          description: 'Bridging technology and business.',
          longDescription: 'ISS focuses on the strategic application of technology in business environments.',
          logo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660320/cict4_qqksfh.jpg',
          banner: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
          established: '2020',
          mission: 'To develop business-savvy technology professionals.',
          vision: 'Leaders in information systems management.',
          values: ['Integrity', 'Strategy', 'Synergy'],
          achievements: ['Digital Transformation Case Competition Winners'],
          members: [
            {
              id: 'iss-president',
              name: 'Gabriel Enrique Villanueva',
              position: 'President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335676/ict2_evnxgu.jpg',
              bio: 'Bridging business and technology through strategic leadership and industry collaboration.',
              joinedDate: '2021',
            },
            {
              id: 'iss-vp',
              name: 'Bianca Marie Fernandez',
              position: 'Vice President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326586/IMG_9662_hxo97w.jpg',
              bio: 'Developing information systems professionals through practical projects and industry engagement.',
              joinedDate: '2022',
            },
            {
              id: 'iss-treasurer',
              name: 'Karl Vincent De Leon',
              position: 'Treasurer',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335682/IMG_4475_w1pvki.jpg',
              bio: 'Managing financial resources for consulting projects and professional development activities.',
              joinedDate: '2023',
            },
          ],
          color: {
            primary: '#059669',
            secondary: '#34d399',
            accent: '#fcd34d',
          },
        },
        {
          id: 'best',
          name: 'BEST',
          fullName: 'Board of European Students of Technology',
          description: 'Connecting students across Europe (and beyond).',
          longDescription: 'BEST provides complementary education and international opportunities.',
          logo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660320/cict4_qqksfh.jpg',
          banner: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
          established: '2015',
          mission: 'Developing students through international cooperation.',
          vision: 'Empowered diversity.',
          values: ['Fun', 'Friendship', 'Improvement'],
          achievements: ['European Student Organization Excellence Award', '100+ International Events Organized'],
          members: [
            {
              id: 'best-president',
              name: 'Marcus Heinrich Weber',
              position: 'President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326595/IMG_7600_maxrip.jpg',
              bio: 'Fostering international cooperation and cultural exchange among technology students across borders.',
              joinedDate: '2022',
            },
            {
              id: 'best-vp',
              name: 'Camille Therese Santiago',
              position: 'Vice President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939565/received_1809661546296324_nwsao0.jpg',
              bio: 'Coordinating complementary education programs and career support for international students.',
              joinedDate: '2022',
            },
            {
              id: 'best-exchange',
              name: 'Hannah Grace Villar',
              position: 'Exchange Coordinator',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1782326578/Entertainment_xoxexz.jpg',
              bio: 'Managing cultural exchange events and international student networking programs.',
              joinedDate: '2023',
            },
          ],
          color: {
            primary: '#7c3aed',
            secondary: '#a78bfa',
            accent: '#c4b5fd',
          },
        },
         {
          id: 'robotcu',
          name: 'ROBOTCU',
          fullName: 'Robotics Club University',
          description: 'Innovating the future through robotics.',
          longDescription: 'ROBOTCU is dedicated to the field of robotics and automation.',
          logo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660320/cict4_qqksfh.jpg',
          banner: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1755790148/529718384_122100992648966778_7029427848362639164_n_geskab.jpg',
          established: '2017',
          mission: 'To build the future, one robot at a time.',
          vision: 'Pioneering robotics innovation.',
          values: ['Innovation', 'Precision', 'Teamwork'],
          achievements: ['RoboCup 2023 Finalists', 'National Robotics Competition Champions'],
          members: [
            {
              id: 'robotcu-president',
              name: 'Fernando Mateo Agustin',
              position: 'President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939316/500122427_681028194557259_7080048757823211543_n_yeecku.jpg',
              bio: 'Leading robotics innovation and competition teams toward national and international recognition.',
              joinedDate: '2021',
            },
            {
              id: 'robotcu-vp',
              name: 'Katrina Mae Domingo',
              position: 'Vice President',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1766939342/500442052_681027907890621_3151875760700323871_n_mkssn9.jpg',
              bio: 'Coordinating workshops and build sessions that bring robotics education to every skill level.',
              joinedDate: '2022',
            },
            {
              id: 'robotcu-engineer',
              name: 'Diego Luis Pascual',
              position: 'Lead Engineer',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1752335673/DSC01719_za78uq.jpg',
              bio: 'Designing and building competition-grade robots while mentoring junior members in engineering fundamentals.',
              joinedDate: '2022',
            },
            {
              id: 'robotcu-research',
              name: 'Samantha Rae Castillo',
              position: 'Research Head',
              photo: 'https://res.cloudinary.com/ddnxfpziq/image/upload/v1756660324/ict4_qnkh2y.jpg',
              bio: 'Exploring AI and automation research to push the boundaries of what student-built robots can achieve.',
              joinedDate: '2023',
            },
          ],
          color: {
            primary: '#dc2626',
            secondary: '#ef4444',
            accent: '#fee2e2',
          },
        },
      ];

    await Organization.insertMany(orgData);
    logger.info('✅ Organizations seeded (5 organizations)');

    logger.info('🎉 Database seeding completed successfully!');
    logger.info('\n📝 Next steps:');
    logger.info('1. Change the default admin password');
    logger.info('2. Start the server with: pnpm dev');
    logger.info('3. Login with: admin@cict.edu / Admin@123456');
    
    process.exit(0);
  } catch (error) {
    logger.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
